### ISSUE TITLE
R&D. Понять что значат метаданные

### ISSUE THREAD

**Issue by PavelMSTU** [kib-sources/stego-mp4-link#1]
Нужно выяснить обо всех метаданных в m4a (mp4) файлах:
![photo_2023-02-04_18-00-11](https://user-images.githubusercontent.com/8336787/216774365-56fc3614-471c-47ea-b5a0-9d507e006c47.jpg)

**DoD:**
1. написан в корне документ meradata.md
2. в документе в виде таблицы все метадата поля с описанием
3. ссылка на документы, откуда взяли информацию

**Comment by yourProgrammist** [comment]
Описка metadata.md
